#!/home/david/ansible/myansible/bin/ansible-playbook

- name: AltSchool Examination Project
  hosts: aws_ec2
  become: true
  become_user: root

  tasks:
    - block:
      - name: Check if Recipient Folder Exists
        stat:
          path: ~/Laravel-Host
        register: projectFolder

      - name: Create Project Folder 
        command: mkdir ~/Laravel-Host
        when: not projectFolder.stat.exists
        register: dirCreate
      - debug: 
          var: dirCreate

      - name: Copy Folder Containing the Files on Remote Server and Change ops.sh Executable Permission
        copy:
          src: ~/Laravel-Host
          dest: ~/
          mode: 0644
        register: clone
      - debug: var=clone

      - name: Change ops.sh Executable Permission
        command: sudo chmod a+x ~/Laravel-Host/ops.sh
        register: chmod
      - debug: var=chmod

      - name: Run Operations
        command: ~/Laravel-Host/ops.sh
        register: ops 
      - debug: var=ops