#!/home/david/ansible/myansible/bin/ansible-playbook

- name: AltSchool Examination Project
  hosts: aws_ec2
  become: true
  become_user: ubuntu
  vars:
    opsFile: ~/Laravel-Host/ops.sh
    opsFolder: ~/Laravel-Host
    laravelFolder: ~/laravel-realworld-example-app
    repo: github.com/DavidHODs/Laravel-Host.git
    laravelRepo: github.com/DavidHODs/laravel-realworld-example-app.git

  tasks:
    - block:
      - name: Check if Recipient Folder Exists
        stat:
          path: "{{ opsFolder }}"
        register: projectFolder
      - debug: 
          var: projectFolder.stat.exists

      - name: Check if Laravel EXample Folder Exists
        stat:
          path: "{{ laravelFolder }}"
        register: laravelOpFolder
      - debug: 
          var: laravelOpFolder.stat.exists

      - name: Delete Project Folder if it Exists 
        command: sudo rm -rf "{{ opsFolder }}"
        when: projectFolder.stat.exists
        register: dirDelete
      - debug: 
          var: dirDelete

      - name: Delete Laravel Folder if it Exists 
        command: sudo rm -rf "{{ laravelFolder }}"
        when: laravelOpFolder.stat.exists
        register: lavDelete
      - debug: 
          var: lavDelete

      - name: Create Laravel Folder if it Does Not Exist 
        command: sudo mkdir "{{ laravelFolder }}"
        when: not laravelOpFolder.stat.exists
        register: lavCreate
      - debug: 
          var: lavCreate


      # - name: Copy Folder Containing the Files on Remote Server and Change ops.sh Executable Permission
      #   copy:
      #     src: ~/Laravel-Host
      #     dest: ~/
      #     mode: 0644
      #   register: clone
      # - debug: var=clone

      # adopted git clone as copying directory was taking ages
      - name: Clone Laravel-Host Git Repo
        command: git clone https://"{{ secret }}"@"{{ repo }}"
        register: clone 
      - debug:
          var: clone

      - name: Clone Laravel Example Git Repo
        command: sudo git clone https://"{{ secret }}"@"{{ laravelRepo}}"
        register: pull
      - debug:
          var: pull

      # - name: Copy File Containing Secret Key
      #   copy:
      #     src: ~/Laravel-Host/.key
      #     dest: ~/Laravel-Host/ 
      #   register: copy 
      # - debug: 
      #     var: copy 

      - name: Change ops.sh Executable Permission
        command: sudo chmod a+x "{{ opsFile }}"
        register: chmod
      - debug: var=chmod

      - name: Run Operations
        command: "{{ opsFile }}"
        register: ops 
      - debug: var=ops